### ISSUE TITLE
screen shot

### ISSUE THREAD

**Issue by zzz945** [zzz945/vue-d3-chart#1]
![2018-03-11 6 24 12](https://user-images.githubusercontent.com/21496977/37252278-81dc109c-2559-11e8-9362-d225130d893c.png)
![2018-03-11 6 24 17](https://user-images.githubusercontent.com/21496977/37252279-820e3928-2559-11e8-8021-779eeb89c765.png)
![2018-03-15 6 22 14](https://user-images.githubusercontent.com/21496977/37457812-00f78876-287e-11e8-84fd-4dcad75c963a.png).githubusercontent.com/21496977/37252281-8270e30c-2559-11e8-9885-1962436688a9.png)
![2018-03-12 2 37 00](https://user-images.githubusercontent.com/21496977/37268873-13fa7d16-2603-11e8-9eb8-95a1b874e68b.png)
![2018-03-12 7 02 56](https://user-images.githubusercontent.com/21496977/37280189-0aa56102-2628-11e8-9977-70f6881e2d4f.png)

**Comment by daipanpan** [comment]
言哥，厉害厉害
